CREATE SEQUENCE sec_contrato_empleados;
CREATE OR REPLACE TRIGGER crea_OID_CONE
BEFORE INSERT ON contrato_empleados
FOR EACH ROW
BEGIN
    SELECT sec_contrato_empleados.NEXTVAL INTO :NEW.OID_CONE FROM DUAL;
END;
/

CREATE SEQUENCE sec_nominas;
CREATE OR REPLACE TRIGGER crea_OID_N
BEFORE INSERT ON nominas
FOR EACH ROW
BEGIN
    SELECT sec_nominas.NEXTVAL INTO :NEW.OID_N FROM DUAL;
END;
/

CREATE SEQUENCE sec_tarea;
CREATE OR REPLACE TRIGGER crea_OID_T
BEFORE INSERT ON tarea
FOR EACH ROW
BEGIN
    SELECT sec_tarea.NEXTVAL INTO :NEW.OID_T FROM DUAL;
END;
/

CREATE SEQUENCE sec_Es_Realizado_Por;
CREATE OR REPLACE TRIGGER crea_OID_REA
BEFORE INSERT ON Es_Realizado_Por
FOR EACH ROW
BEGIN
    SELECT sec_Es_Realizado_Por.NEXTVAL INTO :NEW.OID_REA FROM DUAL;
END;
/

CREATE SEQUENCE sec_Es_empleado_de;
CREATE OR REPLACE TRIGGER crea_OID_ES
BEFORE INSERT ON Es_empleado_de
FOR EACH ROW
BEGIN
    SELECT sec_Es_empleado_de.NEXTVAL INTO :NEW.OID_ES FROM DUAL;
END;
/

CREATE SEQUENCE sec_residencia;
CREATE OR REPLACE TRIGGER crea_OID_R
BEFORE INSERT ON residencia
FOR EACH ROW
BEGIN
    SELECT sec_residencia.NEXTVAL INTO :NEW.OID_R FROM DUAL;
END;
/

CREATE SEQUENCE sec_habitacion;
CREATE OR REPLACE TRIGGER crea_OID_H
BEFORE INSERT ON habitacion
FOR EACH ROW
BEGIN
    SELECT sec_habitacion.NEXTVAL INTO :NEW.OID_H FROM DUAL;
END;
/

CREATE SEQUENCE sec_contrato_residente;
CREATE OR REPLACE TRIGGER crea_OID_CR
BEFORE INSERT ON contrato_residente
FOR EACH ROW
BEGIN
    SELECT sec_contrato_residente.NEXTVAL INTO :NEW.OID_CR FROM DUAL;
END;
/

CREATE SEQUENCE sec_PagoInicial;
CREATE OR REPLACE TRIGGER crea_OID_PIN
BEFORE INSERT ON PagoInicial
FOR EACH ROW
BEGIN
    SELECT sec_PagoInicial.NEXTVAL INTO :NEW.OID_PIN FROM DUAL;
END;
/

CREATE SEQUENCE sec_PagoMensual;
CREATE OR REPLACE TRIGGER crea_OID_PMEN
BEFORE INSERT ON PagoMensual
FOR EACH ROW
BEGIN
    SELECT sec_PagoMensual.NEXTVAL INTO :NEW.OID_PMEN FROM DUAL;
END;
/

CREATE SEQUENCE sec_descuento;
CREATE OR REPLACE TRIGGER crea_OID_DES
BEFORE INSERT ON descuento
FOR EACH ROW
BEGIN
    SELECT sec_descuento.NEXTVAL INTO :NEW.OID_DES FROM DUAL;
END;
/

CREATE SEQUENCE sec_Es_pagado_por;
CREATE OR REPLACE TRIGGER crea_OID_EPP
BEFORE INSERT ON Es_pagado_por
FOR EACH ROW
BEGIN
    SELECT sec_Es_pagado_por.NEXTVAL INTO :NEW.OID_EPP FROM DUAL;
END;
/

CREATE SEQUENCE sec_Pertenece_A;
CREATE OR REPLACE TRIGGER crea_OID_AP
BEFORE INSERT ON Pertenece_A
FOR EACH ROW
BEGIN
    SELECT sec_Pertenece_A.NEXTVAL INTO :NEW.OID_AP FROM DUAL;
END;
/

CREATE SEQUENCE sec_sala;
CREATE OR REPLACE TRIGGER crea_OID_SALA
BEFORE INSERT ON sala
FOR EACH ROW
BEGIN
    SELECT sec_sala.NEXTVAL INTO :NEW.OID_SALA FROM DUAL;
END;
/

CREATE SEQUENCE sec_reservado_por;
CREATE OR REPLACE TRIGGER crea_OID_RP
BEFORE INSERT ON reservado_por
FOR EACH ROW
BEGIN
    SELECT sec_reservado_por.NEXTVAL INTO :NEW.OID_RP FROM DUAL;
END;
/


CREATE SEQUENCE sec_comedor;
CREATE OR REPLACE TRIGGER crea_OID_CO
BEFORE INSERT ON comedor
FOR EACH ROW
BEGIN
    SELECT sec_comedor.NEXTVAL INTO :NEW.OID_CO FROM DUAL;
END;
/

CREATE SEQUENCE sec_pagoMensualSub;
CREATE OR REPLACE TRIGGER crea_OID_PMSUB
BEFORE INSERT ON pagoMensualSub
FOR EACH ROW
BEGIN
    SELECT sec_pagoMensualSub.NEXTVAL INTO :NEW.OID_PMSUB FROM DUAL;
END;
/

CREATE SEQUENCE sec_Es_contratada_por;
CREATE OR REPLACE TRIGGER crea_OID_ECP
BEFORE INSERT ON Es_contratada_por
FOR EACH ROW
BEGIN
    SELECT sec_Es_contratada_por.NEXTVAL INTO :NEW.OID_ECP FROM DUAL;
END;
/


CREATE SEQUENCE sec_tareaSub ;
CREATE OR REPLACE TRIGGER crea_OID_TS
BEFORE INSERT ON tareaSub
FOR EACH ROW
BEGIN
    SELECT sec_tareaSub .NEXTVAL INTO :NEW.OID_TS  FROM DUAL;
END;
/

CREATE SEQUENCE sec_Es_realizado_por_sub  ;
CREATE OR REPLACE TRIGGER crea_OID_REASUB 
BEFORE INSERT ON Es_realizado_por_sub 
FOR EACH ROW
BEGIN
    SELECT sec_Es_realizado_por_sub .NEXTVAL INTO :NEW.OID_REASUB  FROM DUAL;
END;
/


CREATE SEQUENCE sec_habita_en   ;
CREATE OR REPLACE TRIGGER crea_OID_HAB 
BEFORE INSERT ON habita_en 
FOR EACH ROW
BEGIN
    SELECT sec_habita_en .NEXTVAL INTO :NEW.OID_HAB   FROM DUAL;
END;
/

CREATE SEQUENCE sec_usuario_registrado  ;
CREATE OR REPLACE TRIGGER crea_OID_UR
BEFORE INSERT ON usuario_registrado
FOR EACH ROW
BEGIN
    SELECT sec_usuario_registrado .NEXTVAL INTO :NEW.OID_UR   FROM DUAL;
END;
/

CREATE SEQUENCE sec_consulta   ;
CREATE OR REPLACE TRIGGER crea_OID_Consulta 
BEFORE INSERT ON consulta 
FOR EACH ROW
BEGIN
    SELECT sec_consulta .NEXTVAL INTO :NEW.OID_Consulta   FROM DUAL;
END;
/



